### ISSUE TITLE
"You are not allowed to access this page" error

### ISSUE THREAD

**Issue by francisbarton** [Fruitfulcode/anaglyph-lite#5]
Hi

Just installed Anaglyph Lite and in the WordPress theme customisation menu I clicked on the Anaglyph Options button, taking me to wp-admin/admin.php?page=anaglyph_options which gave me the message "Sorry, you are not allowed to access this page."

This is on my own server space. I don't understand why it is not allowing me to access the options page. Please could you help? Thanks.

**Comment by jay2001** [comment]
I think that happens if you don't have the "Redux Framework" installed and activated?

**Comment by francisbarton** [comment]
Thank you - that was it! Sorry. I had installed, but not activated, Redux.
